# Taller preparcial 1 — Sección 3: Pandas
**Ciencia de Datos · Programación II · Universidad Externado de Colombia**

## Instrucciones de entrega (GitHub)
1. Cree un repositorio en GitHub desde su cuenta asociada a su **correo institucional**.
2. Abra el repositorio en **GitHub Codespaces** y suba/cree este cuaderno.
3. Desarrolle cada punto en la celda de código que le sigue.
4. Realice **un commit por cada punto desarrollado**, con un mensaje claro, por ejemplo: `Subseccion 1 - Punto 3: estandarizar Genero`.

## Instrucciones del taller
Resuelva cada punto escribiendo el código en Python/pandas necesario. **A partir de la subsección 2, todas las preguntas asumen que el DataFrame ya fue limpiado con las soluciones de la subsección 1** (salvo que se indique explícitamente lo contrario).

## Contexto
Considere el siguiente `DataFrame` `df`, con información de 12 empleados de una empresa. Ejecute la siguiente celda para crearlo.

In [1]:
import pandas as pd
import numpy as np

datos = {
    "Nombre": ["Mariana", "Esteban", "Camilo", "Juliana", "Nicolas", "Paula",
               "Sebastian", "Laura", "Andres", "Catalina", "Esteban", "Manuela"],
    "Edad": [24, 29, 35, 22, 31, 27, 40, 26, 33, 29, 29, 24],
    "Genero": ["Mujer", "H", "Hombre", "M", "Hombre", "Mujer",
               "H", "Mujer", "Hombre", "M", "H", "Mujer"],
    "Ciudad": ["Bogota", "Medellin", "Cali", "Bogota", "Bucaramanga", "Medellin",
               "Bogota", "Cali", "Pasto", "Bogota", "Medellin", "Bogota"],
    "Departamento": ["Marketing", "Ventas", "IT", np.nan, "Ventas", "Marketing",
                     "IT", np.nan, "Finanzas", "Marketing", "Ventas", "Finanzas"],
    "Salario": [3.8, 4.2, 6.0, 3.2, 4.0, 3.9, 6.3, 3.7, 4.5, 55.0, 4.2, 3.6],
    "AñosExperiencia": [2, 5, 10, -3, 7, 4, 15, 3, 9, 6, 5, 2],
}

df = pd.DataFrame(datos)
df

,Nombre,Edad,Genero,Ciudad,Departamento,Salario,AñosExperiencia
0,Mariana,24,Mujer,Bogota,Marketing,3.8,2
1,Esteban,29,H,Medellin,Ventas,4.2,5
2,Camilo,35,Hombre,Cali,IT,6.0,10
3,Juliana,22,M,Bogota,NaN,3.2,-3
4,Nicolas,31,Hombre,Bucaramanga,Ventas,4.0,7
5,Paula,27,Mujer,Medellin,Marketing,3.9,4
6,Sebastian,40,H,Bogota,IT,6.3,15
7,Laura,26,Mujer,Cali,NaN,3.7,3
8,Andres,33,Hombre,Pasto,Finanzas,4.5,9
9,Catalina,29,M,Bogota,Marketing,55.0,6
10,Esteban,29,H,Medellin,Ventas,4.2,5
11,Manuela,24,Mujer,Bogota,Finanzas,3.6,2

Este conjunto de datos presenta **cinco** problemas de calidad, que se resolverán en la subsección 1.

> **Nota:** en `df` las ciudades están escritas sin tilde (`Medellin`). Tenga esto en cuenta al filtrar.

---
## Subsección 1: Limpieza de datos

**1.** La variable **Departamento** tiene valores faltantes (`NaN`) en las filas de **Juliana** y **Laura**. Escriba el código en pandas que impute estos valores utilizando la **moda** de la variable.

In [2]:
# Escriba aquí su código
# mode() devuelve una Serie ordenada alfabéticamente; [0] toma el primer valor.
# Aquí hay empate (Marketing = 3 y Ventas = 3, con Esteban duplicado); el punto 4
# aún no se ha aplicado. mode()[0] resuelve el empate con "Marketing".
moda = df["Departamento"].mode()[0]
print("Moda:", moda)
df["Departamento"] = df["Departamento"].fillna(moda)
df

Moda: Marketing

,Nombre,Edad,Genero,Ciudad,Departamento,Salario,AñosExperiencia
0,Mariana,24,Mujer,Bogota,Marketing,3.8,2
1,Esteban,29,H,Medellin,Ventas,4.2,5
2,Camilo,35,Hombre,Cali,IT,6.0,10
3,Juliana,22,M,Bogota,Marketing,3.2,-3
4,Nicolas,31,Hombre,Bucaramanga,Ventas,4.0,7
5,Paula,27,Mujer,Medellin,Marketing,3.9,4
6,Sebastian,40,H,Bogota,IT,6.3,15
7,Laura,26,Mujer,Cali,Marketing,3.7,3
8,Andres,33,Hombre,Pasto,Finanzas,4.5,9
9,Catalina,29,M,Bogota,Marketing,55.0,6
10,Esteban,29,H,Medellin,Ventas,4.2,5
11,Manuela,24,Mujer,Bogota,Finanzas,3.6,2

**2.** La variable **AñosExperiencia** tiene un valor negativo en la fila de **Juliana** (`-3`), producto de un error de digitación. Escriba el código en pandas que corrija este valor, convirtiéndolo en positivo.

In [3]:
df["AñosExperiencia"] = df["AñosExperiencia"].abs()
df.head(5)

    Nombre  Edad  Genero       Ciudad Departamento  Salario  AñosExperiencia
0  Mariana    24   Mujer       Bogota    Marketing      3.8                2
1  Esteban    29       H     Medellin       Ventas      4.2                5
2   Camilo    35  Hombre         Cali           IT      6.0               10
3  Juliana    22       M       Bogota    Marketing      3.2                3
4  Nicolas    31  Hombre  Bucaramanga       Ventas      4.0                7

**3.** La variable **Genero** presenta inconsistencias: aparece registrada como `"Hombre"`, `"H"`, `"Mujer"` y `"M"`. Escriba el código en pandas que estandarice esta variable para que solo queden los valores `"Hombre"` y `"Mujer"`.

In [4]:
# Escriba aquí su código
df["Genero"] = df["Genero"].replace({"H": "Hombre", "M": "Mujer"})
df["Genero"].value_counts()

Genero
Mujer     6
Hombre    6
Name: count, dtype: int64

**4.** El `DataFrame` contiene una fila **duplicada**: el empleado **Esteban** aparece registrado dos veces de forma idéntica. Escriba el código en pandas que detecte y elimine las filas duplicadas.

In [5]:
# Escriba aquí su código
print("Filas duplicadas:", df.duplicated().sum())
df = df.drop_duplicates().reset_index(drop=True)
df

Filas duplicadas: 1

,Nombre,Edad,Genero,Ciudad,Departamento,Salario,AñosExperiencia
0,Mariana,24,Mujer,Bogota,Marketing,3.8,2
1,Esteban,29,Hombre,Medellin,Ventas,4.2,5
2,Camilo,35,Hombre,Cali,IT,6.0,10
3,Juliana,22,Mujer,Bogota,Marketing,3.2,3
4,Nicolas,31,Hombre,Bucaramanga,Ventas,4.0,7
5,Paula,27,Mujer,Medellin,Marketing,3.9,4
6,Sebastian,40,Hombre,Bogota,IT,6.3,15
7,Laura,26,Mujer,Cali,Marketing,3.7,3
8,Andres,33,Hombre,Pasto,Finanzas,4.5,9
9,Catalina,29,Mujer,Bogota,Marketing,55.0,6
10,Manuela,24,Mujer,Bogota,Finanzas,3.6,2

**5.** La variable **Salario** de **Catalina** tiene un valor atípico (`55.0`), muy alejado del resto de los datos. Corríjalo asumiendo que se trata de un error de digitación (un cero de más).

In [6]:
# Escriba aquí su código
df.loc[df["Nombre"] == "Catalina", "Salario"] = df.loc[df["Nombre"] == "Catalina", "Salario"] / 10
df[df["Nombre"] == "Catalina"]

     Nombre  Edad Genero  Ciudad Departamento  Salario  AñosExperiencia
9  Catalina    29  Mujer  Bogota    Marketing      5.5                6

**6.** El registro de **Manuela** está desactualizado: en realidad ella tiene **8 años** de experiencia. Escriba el código en pandas que corrija ese dato.

In [7]:
# Escriba aquí su código
df.loc[df["Nombre"] == "Manuela", "AñosExperiencia"] = 8
df[df["Nombre"] == "Manuela"]

     Nombre  Edad Genero  Ciudad Departamento  Salario  AñosExperiencia
10  Manuela    24  Mujer  Bogota     Finanzas      3.6                8

---
## Subsección 2: Exploración, filtrado, consultas, ordenamiento

**1.** Obtenga una descripción estadística completa de **todas** las variables del `DataFrame` ya limpio (tanto numéricas como categóricas).

In [8]:
# Escriba aquí su código
df.describe(include="all")

,Nombre,Edad,Genero,Ciudad,Departamento,Salario,AñosExperiencia
count,11,11.000000,11,11,11,11.000000,11.000000
unique,11,NaN,2,5,4,NaN,NaN
top,Mariana,NaN,Mujer,Bogota,Marketing,NaN,NaN
freq,1,NaN,6,5,5,NaN,NaN
mean,NaN,29.090909,NaN,NaN,NaN,4.427273,6.545455
std,NaN,5.375026,NaN,NaN,NaN,1.037392,3.830500
min,NaN,22.000000,NaN,NaN,NaN,3.200000,2.000000
25%,NaN,25.000000,NaN,NaN,NaN,3.750000,3.500000
50%,NaN,29.000000,NaN,NaN,NaN,4.000000,6.000000
75%,NaN,32.000000,NaN,NaN,NaN,5.000000,8.500000
max,NaN,40.000000,NaN,NaN,NaN,6.300000,15.000000

**2.** Cree un nuevo `DataFrame` llamado `df_num` que contenga **únicamente** las variables numéricas del `DataFrame` original.

In [9]:
# Escriba aquí su código
df_num = df.select_dtypes(include="number")
df_num

    Edad  Salario  AñosExperiencia
0     24      3.8                2
1     29      4.2                5
2     35      6.0               10
3     22      3.2                3
4     31      4.0                7
5     27      3.9                4
6     40      6.3               15
7     26      3.7                3
8     33      4.5                9
9     29      5.5                6
10    24      3.6                8

**3.** Escriba el código en pandas que filtre las personas que cumplen **todas** las siguientes condiciones, e indique cuántos registros la cumplen:

- Tienen edad **impar**, **y**
- además, (son de **Bogotá o** tienen un salario mayor a `4.0`).

In [10]:
# Escriba aquí su código
filtro = df[(df["Edad"] % 2 == 1) & ((df["Ciudad"] == "Bogota") | (df["Salario"] > 4.0))]
print("Registros que cumplen:", len(filtro))
filtro

Registros que cumplen: 4

     Nombre  Edad  Genero    Ciudad Departamento  Salario  AñosExperiencia
1   Esteban    29  Hombre  Medellin       Ventas      4.2                5
2    Camilo    35  Hombre      Cali           IT      6.0               10
8    Andres    33  Hombre     Pasto     Finanzas      4.5                9
9  Catalina    29   Mujer    Bogota    Marketing      5.5                6

**4.** Escriba el código en pandas que permita saber cuántas personas son **mujeres**, **no** son de **Medellín**, y tienen un **salario mayor a 5.3**.

In [11]:
# Escriba aquí su código
resultado = df[(df["Genero"] == "Mujer") & (df["Ciudad"] != "Medellin") & (df["Salario"] > 5.3)]
print("Personas:", len(resultado))
resultado

Personas: 1

     Nombre  Edad Genero  Ciudad Departamento  Salario  AñosExperiencia
9  Catalina    29  Mujer  Bogota    Marketing      5.5                6

**5.** Escriba el código en pandas que determine **cuántas personas** tienen un nombre que **termina en vocal**.

In [12]:
# Escriba aquí su código
termina_vocal = df["Nombre"].str.lower().str[-1].isin(list("aeiou"))
print("Personas con nombre terminado en vocal:", termina_vocal.sum())
df[termina_vocal]

Personas con nombre terminado en vocal: 7

      Nombre  Edad  Genero    Ciudad Departamento  Salario  AñosExperiencia
0    Mariana    24   Mujer    Bogota    Marketing      3.8                2
2     Camilo    35  Hombre      Cali           IT      6.0               10
3    Juliana    22   Mujer    Bogota    Marketing      3.2                3
5      Paula    27   Mujer  Medellin    Marketing      3.9                4
7      Laura    26   Mujer      Cali    Marketing      3.7                3
9   Catalina    29   Mujer    Bogota    Marketing      5.5                6
10   Manuela    24   Mujer    Bogota     Finanzas      3.6                8

**6.** Escriba el código en pandas que muestre a los **3 empleados mejor pagados**, ordenados de mayor a menor salario.

In [13]:
# Escriba aquí su código
df.sort_values("Salario", ascending=False).head(3)

      Nombre  Edad  Genero  Ciudad Departamento  Salario  AñosExperiencia
6  Sebastian    40  Hombre  Bogota           IT      6.3               15
2     Camilo    35  Hombre    Cali           IT      6.0               10
9   Catalina    29   Mujer  Bogota    Marketing      5.5                6

**7.** Escriba el código en pandas que ordene el `DataFrame` de forma **ascendente por Salario** y, en caso de empate, de forma **descendente por AñosExperiencia**.

In [14]:
# Escriba aquí su código
df.sort_values(by=["Salario", "AñosExperiencia"], ascending=[True, False])

,Nombre,Edad,Genero,Ciudad,Departamento,Salario,AñosExperiencia
3,Juliana,22,Mujer,Bogota,Marketing,3.2,3
10,Manuela,24,Mujer,Bogota,Finanzas,3.6,8
7,Laura,26,Mujer,Cali,Marketing,3.7,3
0,Mariana,24,Mujer,Bogota,Marketing,3.8,2
5,Paula,27,Mujer,Medellin,Marketing,3.9,4
4,Nicolas,31,Hombre,Bucaramanga,Ventas,4.0,7
1,Esteban,29,Hombre,Medellin,Ventas,4.2,5
8,Andres,33,Hombre,Pasto,Finanzas,4.5,9
9,Catalina,29,Mujer,Bogota,Marketing,5.5,6
2,Camilo,35,Hombre,Cali,IT,6.0,10
6,Sebastian,40,Hombre,Bogota,IT,6.3,15

**8.** Los siguientes dos puntos deben resolverse **en el orden en que aparecen**, ya que cada uno parte del resultado del anterior.

**8 (a).** Agregue al `DataFrame` un nuevo registro, con los datos de un empleado ficticio de su elección (respetando las columnas existentes).

In [15]:
# Escriba aquí su código
df.loc[len(df)] = ["Santiago", 30, "Hombre", "Bogota", "IT", 5.0, 6]
df.tail(3)

      Nombre  Edad  Genero  Ciudad Departamento  Salario  AñosExperiencia
9   Catalina    29   Mujer  Bogota    Marketing      5.5                6
10   Manuela    24   Mujer  Bogota     Finanzas      3.6                8
11  Santiago    30  Hombre  Bogota           IT      5.0                6

**8 (b).** Elimine el registro que agregó en el punto anterior.

In [16]:
# Escriba aquí su código
df = df.drop(index=df.index[-1])
df.tail(3)

      Nombre  Edad  Genero  Ciudad Departamento  Salario  AñosExperiencia
8     Andres    33  Hombre   Pasto     Finanzas      4.5                9
9   Catalina    29   Mujer  Bogota    Marketing      5.5                6
10   Manuela    24   Mujer  Bogota     Finanzas      3.6                8

**9.** Escriba el código en pandas que convierta todos los valores de la columna **Nombre** a **mayúsculas**.

In [17]:
# Escriba aquí su código
df["Nombre"] = df["Nombre"].str.upper()
df.head()

    Nombre  Edad  Genero       Ciudad Departamento  Salario  AñosExperiencia
0  MARIANA    24   Mujer       Bogota    Marketing      3.8                2
1  ESTEBAN    29  Hombre     Medellin       Ventas      4.2                5
2   CAMILO    35  Hombre         Cali           IT      6.0               10
3  JULIANA    22   Mujer       Bogota    Marketing      3.2                3
4  NICOLAS    31  Hombre  Bucaramanga       Ventas      4.0                7

**10.** Cree una nueva variable llamada `SalarioPorAño`, que sea el resultado de dividir el **Salario** entre los **AñosExperiencia** de cada empleado.

In [18]:
# Escriba aquí su código
df["SalarioPorAño"] = df["Salario"] / df["AñosExperiencia"]
df.head()

,Nombre,Edad,Genero,Ciudad,Departamento,Salario,AñosExperiencia,SalarioPorAño
0,MARIANA,24,Mujer,Bogota,Marketing,3.8,2,1.900000
1,ESTEBAN,29,Hombre,Medellin,Ventas,4.2,5,0.840000
2,CAMILO,35,Hombre,Cali,IT,6.0,10,0.600000
3,JULIANA,22,Mujer,Bogota,Marketing,3.2,3,1.066667
4,NICOLAS,31,Hombre,Bucaramanga,Ventas,4.0,7,0.571429

**11.** Cree una nueva variable categórica llamada `Antiguedad`, a partir de **AñosExperiencia**, de la siguiente manera:

- `"nuevo"` si tiene **menos de 2 años** de experiencia.
- `"experto"` si tiene **entre 2 y 5 años** de experiencia (ambos incluidos).
- `"antiguo"` si tiene **6 años o más** de experiencia.

In [19]:
# Escriba aquí su código
df["Antiguedad"] = pd.cut(df["AñosExperiencia"],
                          bins=[-np.inf, 1, 5, np.inf],
                          labels=["nuevo", "experto", "antiguo"])
df[["Nombre", "AñosExperiencia", "Antiguedad"]]

       Nombre  AñosExperiencia Antiguedad
0     MARIANA                2    experto
1     ESTEBAN                5    experto
2      CAMILO               10    antiguo
3     JULIANA                3    experto
4     NICOLAS                7    antiguo
5       PAULA                4    experto
6   SEBASTIAN               15    antiguo
7       LAURA                3    experto
8      ANDRES                9    antiguo
9    CATALINA                6    antiguo
10    MANUELA                8    antiguo

---
## Subsección 3: Agrupamiento (`groupby`)

Todas las preguntas de esta sección asumen que ya se creó la variable `Antiguedad` de la Subsección 2.

**1.** Calcule el **salario promedio** por `Departamento`, ordenado de mayor a menor.

In [20]:
# Escriba aquí su código
df.groupby("Departamento")["Salario"].mean().sort_values(ascending=False)

Departamento
IT           6.15
Ventas       4.10
Finanzas     4.05
Marketing    4.02
Name: Salario, dtype: float64

**2.** Cuente cuántos empleados hay de cada `Genero`.

In [21]:
# Escriba aquí su código
df.groupby("Genero").size()

Genero
Hombre    5
Mujer     6
dtype: int64

**3.** Encuentre el salario **máximo** y **mínimo** en cada `Ciudad`.

In [22]:
# Escriba aquí su código

**4.** Calcule, para cada categoría de `Antiguedad`, el promedio de **AñosExperiencia** y de **Salario** al mismo tiempo.

In [23]:
# Escriba aquí su código

**5.** Cuente cuántos empleados hay en cada combinación de `Departamento` y `Genero`.

In [24]:
# Escriba aquí su código

---
## Subsección 4: Ramas y viaje por las versiones del repositorio (Git)

Hasta ahora usted ha hecho **un commit por cada punto**. Cada commit es una **fotografía** (*snapshot*) completa del repositorio en un momento dado, identificada por un código único llamado **hash** (por ejemplo `a3f9c1e`). En esta subsección aprenderá a:

1. Trabajar en una **rama** (*branch*) sin afectar la versión principal del proyecto.
2. **Unir** (*merge*) esa rama con la rama principal.
3. **Viajar** por las diferentes versiones del repositorio: ver, comparar, recuperar y deshacer cambios.

> **Importante:** los comandos de Git se escriben en la **terminal** de Codespaces (`Ctrl + ñ` o menú *Terminal → New Terminal*). Los comandos que **solo consultan** información (`git log`, `git show`, `git diff`, `git status`) también pueden ejecutarse desde una celda del cuaderno anteponiendo `!`, por ejemplo `!git log --oneline`. Los comandos que **cambian de versión** (`git switch`, `git checkout`, `git merge`, `git revert`) ejecútelos **siempre desde la terminal**, porque modifican el archivo del cuaderno que usted tiene abierto.

### 4.1 ¿Qué es una rama?

Una **rama** es simplemente un **puntero** con nombre que apunta a un commit. La rama principal suele llamarse `main`. Cuando usted crea una rama nueva, Git no copia archivos: solo crea un nuevo puntero que avanzará con los commits que haga en ella, mientras `main` se queda quieta.

`HEAD` es otro puntero especial que indica **en qué lugar está usted parado** en este momento (normalmente, en la punta de una rama).

```
                         C4 ── C5      ← analisis-extra  (HEAD)
                        /
C0 ── C1 ── C2 ── C3 ──┘               ← main
```

Después de unir (`merge`) la rama `analisis-extra` en `main`, ambas historias quedan juntas:

```
C0 ── C1 ── C2 ── C3 ── C4 ── C5       ← main, analisis-extra
```

**¿Para qué sirven las ramas?** Para experimentar, desarrollar una funcionalidad nueva o resolver un problema **sin dañar** la versión estable. Si el experimento sale mal, basta con abandonar la rama; si sale bien, se une a `main`.

| Comando | Qué hace |
|---|---|
| `git branch` | Lista las ramas locales (la actual aparece con `*`). |
| `git branch -a` | Lista también las ramas remotas (las de GitHub). |
| `git switch -c <rama>` | Crea una rama nueva y se cambia a ella (equivale a `git checkout -b <rama>`). |
| `git switch <rama>` | Se cambia a una rama existente. |
| `git push -u origin <rama>` | Sube la rama a GitHub por primera vez. |
| `git merge <rama>` | Une la rama indicada **dentro de la rama actual**. |
| `git branch -d <rama>` | Borra una rama local que ya fue unida. |

> En Codespaces también puede ver y cambiar de rama haciendo clic en el nombre de la rama en la **esquina inferior izquierda** de la ventana, o desde el panel **Source Control**.

### 4.2 Trabajo en una rama

**1.** Desde la terminal, verifique en qué rama se encuentra y que no tenga cambios pendientes. Luego cree una rama llamada `analisis-extra`, cámbiese a ella y súbala a GitHub:

```bash
git status
git branch
git switch -c analisis-extra
git push -u origin analisis-extra
```

Ejecute en la celda siguiente `!git branch` y explique qué significa el asterisco `*`.

In [25]:
# Escriba aquí su comando (con ! al inicio para ejecutarlo desde el cuaderno)

**Respuesta:** _escriba aquí su respuesta_

Los puntos **2** a **5** deben desarrollarse **dentro de la rama `analisis-extra`**, haciendo **un commit por cada punto** (y `git push` al final).

**2.** Construya una **tabla dinámica** (`pd.pivot_table`) que muestre el **salario promedio** por `Departamento` (filas) y `Genero` (columnas).

In [26]:
# Escriba aquí su código

**3.** Calcule el **porcentaje** de empleados que hay en cada categoría de `Antiguedad` (sugerencia: `value_counts(normalize=True)`).

In [27]:
# Escriba aquí su código

**4.** Encuentre, para cada `Departamento`, el **nombre del empleado con más AñosExperiencia** (sugerencia: `groupby` + `idxmax`).

In [28]:
# Escriba aquí su código

**5.** Muestre las ciudades cuyo **salario promedio** es **mayor a 4.0**, junto con cuántos empleados tiene cada una (sugerencia: `groupby` + `agg` + filtro).

In [29]:
# Escriba aquí su código

**6.** Ejecute el siguiente comando, que dibuja la historia del repositorio como un grafo:

```bash
git log --oneline --graph --all
```

Responda: ¿en qué commit está `main`? ¿En qué commit está `analisis-extra`? ¿Cuántos commits tiene `analisis-extra` que **no** tiene `main`?

In [30]:
# Escriba aquí su comando (con ! al inicio para ejecutarlo desde el cuaderno)

**Respuesta:** _escriba aquí su respuesta_

**7.** Regrese a la rama `main` (**desde la terminal**) y observe el cuaderno: ¿aparecen las soluciones de los puntos 2 a 5? Explique por qué.

```bash
git switch main
```

> VS Code recargará el cuaderno automáticamente al cambiar de rama. **Guarde y haga commit antes de cambiar de rama**; si hay cambios sin guardar, Git no le permitirá cambiarse (o se los llevará a la otra rama).

**Respuesta:** _escriba aquí su respuesta_

**8.** Estando en `main`, una los cambios de la rama `analisis-extra` y súbalos a GitHub:

```bash
git merge analisis-extra
git push
```

Vuelva a ejecutar `git log --oneline --graph --all` y describa qué cambió respecto al punto 6.

> En GitHub la unión de ramas normalmente se hace mediante un **Pull Request** (pestaña *Pull requests → New pull request*), que permite revisar los cambios antes de unirlos. Puede hacerlo así en lugar de `git merge` si lo prefiere.

In [31]:
# Escriba aquí su comando (con ! al inicio para ejecutarlo desde el cuaderno)

**Respuesta:** _escriba aquí su respuesta_

### 4.3 Viajar por las versiones del repositorio

Como cada commit es una fotografía completa, Git permite **volver a cualquier punto de la historia**. Estas son las herramientas principales, de la más inofensiva a la más peligrosa:

| Comando | Qué hace | ¿Modifica la historia? |
|---|---|---|
| `git log --oneline` | Lista los commits (hash corto + mensaje). | No |
| `git show <hash>` | Muestra qué cambió en un commit concreto. | No |
| `git diff <hash1> <hash2>` | Compara dos versiones. | No |
| `git switch --detach <hash>` | **Viaja** a un commit antiguo para verlo (modo *detached HEAD*). | No |
| `git switch main` | Regresa al presente. | No |
| `git restore --source=<hash> <archivo>` | Trae **un archivo** tal como estaba en ese commit. | No (queda como cambio pendiente) |
| `git revert <hash>` | Crea un **commit nuevo** que deshace lo que hizo `<hash>`. | No, **agrega** historia (seguro) |
| `git reset --hard <hash>` | Mueve la rama hacia atrás y **borra** los commits posteriores. | **Sí** (peligroso) |

**Modo *detached HEAD*.** Cuando usted viaja a un commit antiguo, `HEAD` deja de apuntar a una rama y apunta directamente a ese commit:

```
C0 ── C1 ── C2 ── C3 ── C4 ── C5   ← main
             ↑
            HEAD  (usted está aquí, "de visita" en el pasado)
```

Puede mirar, ejecutar y explorar libremente. Si hace cambios ahí y quiere conservarlos, cree una rama con `git switch -c <nombre>`; si no, simplemente regrese con `git switch main`.

**`revert` vs `reset`.** `git revert` es la forma **segura** de deshacer, porque no borra nada: agrega un commit que invierte los cambios, y la historia en GitHub sigue siendo coherente. `git reset --hard` **reescribe** la historia; si esos commits ya estaban en GitHub, obligará a hacer `git push --force` y puede causar problemas a otros colaboradores. **En este curso use `revert`.**

> **Desde GitHub (sin terminal):** en la página del repositorio haga clic en el contador de **commits** (icono de reloj, *History*). Allí verá la lista de commits; al abrir uno verá sus cambios, y con el botón **Browse files** (`<>`) podrá navegar el repositorio completo tal como estaba en ese momento.

**9.** Liste todos los commits del repositorio en formato de una línea. Identifique el **hash** del commit en el que resolvió el **Punto 3 de la Subsección 1** (estandarizar `Genero`) y muestre qué cambió en él con `git show <hash> --stat`.

In [32]:
# Escriba aquí su comando (con ! al inicio para ejecutarlo desde el cuaderno)

**Respuesta:** _escriba aquí su respuesta_

**10.** Use `git diff` para comparar el commit del **Punto 1 de la Subsección 1** con el commit más reciente (`HEAD`), mostrando solo el resumen de archivos modificados:

```bash
git diff <hash_punto1> HEAD --stat
```

> Los cuadernos `.ipynb` son archivos JSON, por lo que el `diff` completo es difícil de leer. Para verlos de forma más amigable puede usar la pestaña **Source Control** de VS Code/Codespaces, que muestra el diff del cuaderno celda por celda.

In [33]:
# Escriba aquí su comando (con ! al inicio para ejecutarlo desde el cuaderno)

**11.** **Viaje en el tiempo.** Desde la terminal, viaje al commit en el que resolvió el **Punto 1 de la Subsección 1**:

```bash
git switch --detach <hash_punto1>
```

Abra el cuaderno y observe qué puntos aparecen resueltos. Ejecute `git status` y lea el mensaje. Luego **regrese al presente**:

```bash
git switch main
```

Responda: ¿qué puntos estaban resueltos en esa versión? ¿Qué significa el mensaje *HEAD detached at …*?

**Respuesta:** _escriba aquí su respuesta_

**12.** **Deshacer un error con `revert`.** Simule un error: borre el código de la solución de **uno** de los puntos, guarde y haga commit con el mensaje `Error: borré una solución por accidente` (y `git push`). Luego deshaga ese commit **sin borrar la historia**:

```bash
git log --oneline          # copie el hash del commit con el error
git revert <hash_error>    # se abrirá un editor con el mensaje; guárdelo y ciérrelo
git push
```

Verifique que la solución volvió a aparecer en el cuaderno y ejecute `git log --oneline -5`. ¿Cuántos commits nuevos aparecen? ¿Por qué `revert` es preferible a `reset --hard` en un repositorio compartido?

In [34]:
# Escriba aquí su comando (con ! al inicio para ejecutarlo desde el cuaderno)

**Respuesta:** _escriba aquí su respuesta_

**13.** **Marcar una versión con una etiqueta (tag).** Una etiqueta es un nombre fijo para un commit importante (por ejemplo, la versión que se entrega). Cree una etiqueta para su versión final y súbala a GitHub:

```bash
git tag v1.0-preparcial
git push origin v1.0-preparcial
```

Así, en el futuro podrá volver exactamente a esa versión con `git switch --detach v1.0-preparcial`. Verifique en GitHub que la etiqueta aparece en la sección **Tags** (o *Releases*) del repositorio.

In [35]:
# Escriba aquí su comando (con ! al inicio para ejecutarlo desde el cuaderno)